set -sg escape-time 10
set-option -g focus-events on
set-window-option -g mode-keys vi

# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# set -g @plugin 'dracula/tmux'
# set -g @dracula-plugins "git, ssh-session, attached-clients, time"
# set -g @dracula-show-powerline true
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon hostname
# set -g @dracula-border-contrast true
# set -g @dracula-show-empty-plugins false
# set -g @dracula-day-month true

run '~/.tmux/plugins/tpm/tpm'

