set -sg escape-time 10
set-option -g focus-events on
set-window-option -g mode-keys vi

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

## Status bar customization
set-option -g status-bg black
set-option -g status-fg white 

